# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('directors', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('genres', models.TextField()),
            ],
        ),
    ]
